# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pinger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency', models.FloatField(verbose_name='latency in ms')),
                ('datetime', models.DateTimeField(verbose_name='latency time')),
            ],
            options={
                'verbose_name': 'Ping entry',
                'verbose_name_plural': 'Ping entries',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('description', models.TextField(default='No description', verbose_name='Server description')),
            ],
        ),
        migrations.AddField(
            model_name='pingentry',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinger.Server'),
        ),
    ]
