# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=255, verbose_name='IP or host'),
        ),
    ]
