# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinger', '0002_auto_20170914_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='ip',
            new_name='host',
        ),
    ]
